version: "3"
services:
  # app:
  #   container_name: express-mongo
  #   restart: always
  #   build: ./api/
  #   ports:
  #     - "80:3000"
  #   volumes:
  #     - .:/app
  #   links:
  #     - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"